apiVersion: v1
kind: Pod
metadata:
  name: "webapp"
  namespace: default
spec:
  containers:
  - name: nginx
    image: "nginx:latest"
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: DB_HOST
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
  - name: agentx
    image: "agentx:latest"
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: DB_HOST
    ports:
    - containerPort: 8080
      name: http
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
  volumes:
  - name: localtime
    hostPath:
      path: /usr/share/zoneinfo/Asia/Shanghai
  restartPolicy: Always
