apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
  - port: 80 #internal port
    targetPort: 8080 #the port in which the pod is listening
