apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-port-app
  namespace: default
  labels:
    app: multi-port-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-port-app
  template:
    metadata:
      labels:
        app: multi-port-app
    spec:
      containers:
      - name: multi-port-container
        image: zyadtarek/custom-apache-port443:tagname
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 443
          name: https-port
        - containerPort: 80
          name: http-port


