apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: multi-port-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
