apiVersion: v1
kind: Pod
metadata:
  name: new-web-pod
  labels:
    app: new-web
spec:
  containers:
  - name: new-web-container
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
