apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: old-web
  template:
    metadata:
      labels:
        app: old-web
    spec:
      containers:
      - name: old-web-container
        image: nginx:alpine
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
